//go:build ignore

package main

import (
	"io"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

func cleanName(name string) string {
	name = strings.TrimSuffix(strings.ReplaceAll(name, "-", ""), ".txt")
	r := []rune(name)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

func main() {
	// During `go generate`, the working directory is the module root.
	base := filepath.Join("..", "..", "internal", "icons")
	txtDir := filepath.Join(base, "txt")
	outFile := filepath.Join(base, "icons.go")

	files, err := os.ReadDir(txtDir)
	if err != nil {
		panic(err)
	}

	out, err := os.Create(outFile)
	if err != nil {
		panic(err)
	}
	defer out.Close()

	out.Write([]byte("// Package icons is autogenerated; DO NOT EDIT.\n"))
	out.Write([]byte("package icons\n\nconst (\n"))

	for _, f := range files {
		if !strings.HasSuffix(f.Name(), ".txt") {
			continue
		}

		name := cleanName(f.Name())
		out.Write([]byte("// " + name + " generated from " + f.Name() + "\n"))
		out.Write([]byte(name + " = `"))

		file, err := os.Open(filepath.Join(txtDir, f.Name()))
		if err != nil {
			panic(err)
		}
		io.Copy(out, file)
		file.Close()

		out.Write([]byte("`\n"))
	}

	out.Write([]byte(")\n"))
}
